# docker-compose.yml
version: "3"
services:

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: frontend-app
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ../frontend/.env
    restart: always
    volumes:
      - ../frontend:/app
      - /app/node_modules

  backend:
    container_name: backend
    build: .
    depends_on:
      - database
    environment:
        PG_HOST: database
        PG_PORT: 5432
        PG_USER: app_user
        PG_PASSWORD: coding_test_password
        PG_DATABASE: datatys_db
        SECRET: test-dev-secret
    # env_file:
    #   - .env
    volumes:
      - .:/app/
    working_dir: /app
    command: npm run start
    ports:
      - "3002:3002"

  database:
    container_name: database
    image: timescale/timescaledb-postgis:latest-pg12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: coding_test_password
      POSTGRES_DB: datatys_db
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./sql/insert.sql:/docker-entrypoint-initdb.d/2-insert.sql